# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
  categories:
    - title: Fixed Bugs 🐞
      labels:
        - bug
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Breaking Changes 🚧
      labels:
        - breaking-change
    - title: Other Changes
      labels:
        - "*"
