name: CI

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: giraffate/clippy-action@v1
      with:
        reporter: 'github-pr-review'        
    - name: Print stable Rust version
      run: rustc --version
    - name: Formatter
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Code coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
      run: |        
        cargo llvm-cov --html
#        gh pr comment ${{ github.event.pull_request.number }} -F target/llvm-cov/html/index.html --repo ${{ github.repository }}